/* THE BLACK ARCHIVE — edit SETTINGS below before publishing. */
const SETTINGS={
  recipientName:"OPERATIVE",
  senderCodename:"THE KEEPER",
  // The final clue derives 1327. Set your physical lock to 1327,
  // or edit deriveCode() and this setting together.
  physicalLockCode:"1327",
  photoPath:"assets/memory.jpg",
  quoteAnswers:["deaf","entire","voice","listening","breathe"],
  restaurantAnswers:["rigveda"],
  dishAnswers:["paneer peshawari","peshawari paneer"]
};
const memories=[
 ["The day we first started speaking","05-02-22",1],
 ["The day we officially became us","17-03-22",2],
 ["Our first ever date","21-03-22",3],
 ["Our first ever kiss","03-04-22",4],
 ["The day you ran away and I came to console you","13-05-22",5],
 ["The first time I came to your house and gave you a hickey","27-06-22",6],
 ["The surprise pickup outside your house","14-07-23",7],
 ["The Mehrangarh trip","31-07-23",8]
];
const opening=[
 {q:"The song you danced to — the Instagram video I watched over and over. Which track?",a:["Shivers","Perfect","Levitating","Until I Found You"],c:0},
 {q:"What drink did I used to bring whenever I visited you?",a:["Mogu Mogu","Cold coffee","Chocolate milk","Lemon soda"],c:0},
 {q:"What car did you take your driving lessons in?",a:["Wagon R","Swift","i10","Baleno"],c:0}
];
const tricky=[
 {q:"Where did our first kiss happen?",a:["The back seat of a cab","Outside a café","At home","During the Mehrangarh trip"],c:0},
 {q:"Which date marks when we officially became a couple?",a:["05-02-22","17-03-22","21-03-22","03-04-22"],c:1},
 {q:"Which happened earliest?",a:["First date","First kiss","The day we first started speaking","Mehrangarh trip"],c:2}
];
const stageEl=document.getElementById("stage");
let openingIndex=0,trickyIndex=0,quoteAttempts=0,timeline=[],photoOrder=[],selectedTile=null;
function norm(s){return String(s??"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[’']/g,"").replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," ")}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function render(n,html,total=7){document.getElementById("progressText").textContent=`ACCESS POINT ${String(n).padStart(2,"0")} / ${String(total).padStart(2,"0")}`;document.getElementById("progressBar").style.width=(n/total*100)+"%";stageEl.innerHTML=html;window.scrollTo({top:0,behavior:"smooth"})}
function feedback(id,msg,good=false){const e=document.getElementById(id);if(e){e.textContent=msg;e.className="feedback"+(good?" good":"")}}
function accepted(value,answers){return answers.some(a=>norm(a)===norm(value))}
function openingScreen(){render(1,`<div class="eyebrow">UNAUTHORISED ACCESS DETECTED // 01</div><div class="stamp">CONFIDENTIAL</div><h1>The Black<br>Archive.</h1><p>Somewhere inside this file is an object that was never meant to be found by anyone else.</p><p>It belongs to <strong>${escapeHTML(SETTINGS.recipientName)}</strong>. It was selected by <strong>${escapeHTML(SETTINGS.senderCodename)}</strong>. It has been sealed behind a code that should not be guessed.</p><div class="panel"><div class="panel-label">MISSION BRIEF // READ CAREFULLY</div><p style="margin:0">Recover the evidence. Trust dates. Question obvious answers. One memory will lead to another. Random guesses will not open the archive.</p></div><p class="small">CASE STATUS: SEALED<br>ACCESS LEVEL: PERSONAL<br>UNAUTHORISED EXIT: DISCOURAGED</p><button class="primary" onclick="quotePuzzle()">OPEN THE CASE FILE →</button>`)}
function quotePuzzle(){render(2,`<div class="eyebrow">EVIDENCE 01 // RECOVERED TEXT</div><h2>A sentence with missing pieces.</h2><p class="small">RECOVERED: 09 MAR 2022 // SOURCE: THE KEEPER</p><div class="rule"></div><p class="quote">You know what would be perfect, being <input id="q0" aria-label="missing word one"> to the <input id="q1" aria-label="missing word two"> world and just hearing your words and your <input id="q2" aria-label="missing word three"> and <input id="q3" aria-label="missing word four"> to you <input id="q4" aria-label="missing word five">.</p><p class="small">Five blanks. Exact words. Order matters. Ignore capitalisation and punctuation.</p><button class="primary" onclick="checkQuote()">VERIFY FRAGMENT</button><div id="qfb" class="feedback"></div><div class="rule"></div><p class="small">HINT // One blank describes an inability to hear. The last is a quiet, involuntary sound of being alive.</p>`);for(let i=0;i<5;i++)document.getElementById("q"+i).addEventListener("keydown",e=>{if(e.key==="Enter")checkQuote()})}
function checkQuote(){let vals=SETTINGS.quoteAnswers.map((_,i)=>document.getElementById("q"+i).value);if(vals.every((v,i)=>norm(v)===norm(SETTINGS.quoteAnswers[i]))){feedback("qfb","FRAGMENT VERIFIED. The archive remembers the words you once wrote.",true);setTimeout(paintPuzzle,500)}else{quoteAttempts++;feedback("qfb",quoteAttempts<3?"FRAGMENT CORRUPTED. Check every blank; the order matters.":"HINT UNLOCKED: unable to hear / all of it / the sound you recognise / paying attention / air moving in and out.")}}
function paintPuzzle(){render(3,`<div class="eyebrow">EVIDENCE 02 // PAINT TRANSFER</div><h2>Two dates. Two hands. One beginning.</h2><p>In the living room, paint became a record. Two handprints were pressed onto a canvas. The dates ran from left to right.</p><div class="panel"><div class="panel-label">CANVAS LOG // LEFT → RIGHT</div><p style="margin:0"><strong>05-02-22</strong> <span style="color:var(--muted)">→</span> <strong>17-03-22</strong></p><p class="small" style="margin-bottom:0">One marks when we first started speaking. The other marks when we officially became a couple.</p></div><label for="pd1">Which date marks when we first started speaking?</label><input id="pd1" type="text" placeholder="DD-MM-YY"><label for="pd2">Which date marks when we officially came together?</label><input id="pd2" type="text" placeholder="DD-MM-YY"><button class="primary" onclick="checkPaint()">MATCH THE HANDPRINTS</button><div id="pfb" class="feedback"></div><div class="rule"></div><p class="small">ARCHIVE NOTE: The order is important. Beginning and becoming are not the same event.</p>`)}
function checkPaint(){let a=norm(document.getElementById("pd1").value).replace(/\s/g,"").replaceAll("/","-"),b=norm(document.getElementById("pd2").value).replace(/\s/g,"").replaceAll("/","-");let okA=["05-02-22","5-2-22","050222"].includes(a),okB=["17-03-22","17-3-22","170322"].includes(b);if(okA&&okB){feedback("pfb","BOTH MARKS MATCH. Another drawer opens.",true);setTimeout(timelinePuzzle,500)}else feedback("pfb","NO MATCH. Read the canvas from LEFT to RIGHT. Enter both dates in day-month-year order.")}
function timelinePuzzle(){timeline=[...memories].sort(()=>Math.random()-.5);render(4,`<div class="eyebrow">EVIDENCE 03 // CHRONOLOGY BREACH</div><h2>Which memory came first?</h2><p>The archive's timeline has been tampered with. Restore the memories from earliest to latest.</p><p class="small">Use the ↑ and ↓ controls. The order of dates matters as much as the memories themselves.</p><div id="timeline" class="memory-list">${timeline.map((m,i)=>memoryRow(m,i)).join("")}</div><button class="primary" onclick="checkTimeline()">RESTORE TIMELINE</button><div id="tfb" class="feedback"></div><div class="rule"></div><p class="small">WARNING: A first conversation is not the same thing as a first date.</p>`)}
function memoryRow(m,i){return `<div class="memory"><div class="memory-text">${escapeHTML(m[0])}</div><span class="memory-date">${m[1]}</span><div class="move"><button aria-label="Move up" onclick="moveMemory(${i},-1)">↑</button><button aria-label="Move down" onclick="moveMemory(${i},1)">↓</button></div></div>`}
function moveMemory(i,d){let j=i+d;if(j<0||j>=timeline.length)return;[timeline[i],timeline[j]]=[timeline[j],timeline[i]];document.getElementById("timeline").innerHTML=timeline.map((m,k)=>memoryRow(m,k)).join("")}
function checkTimeline(){if(timeline.every((m,i)=>m[2]===i+1)){feedback("tfb","TIMELINE RESTORED. Eight memories. One continuous story.",true);setTimeout(restaurantPuzzle,500)}else feedback("tfb","TIMELINE REJECTED. Earliest date first; latest date last. Try again.")}
function restaurantPuzzle(){render(5,`<div class="eyebrow">EVIDENCE 04 // LOCATION TRACE</div><h2>A table for two.</h2><p>One of your favourite places to eat holds another piece of the file. The dish is specific. The location is not a city — it is the restaurant itself.</p><div class="panel"><div class="panel-label">FRAGMENT FROM A MEMORY</div><p style="margin:0;font:23px 'Playfair Display',serif;color:var(--text)">Paneer Peshawari.</p><p class="small" style="margin-bottom:0">JODHPUR // REPEATED VISITS // TABLE UNKNOWN</p></div><label for="rest">Name the restaurant.</label><input id="rest" type="text" placeholder="Restaurant name"><label for="dish">Name the dish.</label><input id="dish" type="text" placeholder="Dish name"><button class="primary" onclick="checkRestaurant()">CROSS-REFERENCE MEMORY</button><div id="rfb" class="feedback"></div><div class="rule"></div><p class="small">HINT // One answer is a place. The other is what you order there.</p>`)}
function checkRestaurant(){if(accepted(document.getElementById("rest").value,SETTINGS.restaurantAnswers)&&accepted(document.getElementById("dish").value,SETTINGS.dishAnswers)){feedback("rfb","LOCATION VERIFIED: RIGVEDA. DISH VERIFIED: PANEER PESHAWARI.",true);setTimeout(openingQuiz,500)}else feedback("rfb","NO MATCH. You need BOTH the restaurant name and the exact paneer dish.")}
function openingQuiz(){openingIndex=0;showOpeningQuestion()}
function showOpeningQuestion(){let q=opening[openingIndex];render(6,`<div class="eyebrow">EVIDENCE 05.${openingIndex+1} // INTERROGATION</div><h2>Details betray the truth.</h2><p>${escapeHTML(q.q)}</p><div class="options">${q.a.map((a,i)=>`<button class="option" onclick="answerOpening(${i})"><span class="letter">${String.fromCharCode(65+i)}</span><span>${escapeHTML(a)}</span></button>`).join("")}</div><div id="ofb" class="feedback"></div><p class="small">Correct answers open the next sealed file. Wrong answers do not cost a life — but they do cost time.</p>`,8)}
function answerOpening(i){if(i!==opening[openingIndex].c){feedback("ofb","INCORRECT. The archive rejects confident guessing. Try again.");return}feedback("ofb","VERIFIED. "+["The file confirms it. Some things are replayed for a reason.","A small detail. An unforgettable pattern.","Vehicle record confirmed."][openingIndex],true);openingIndex++;if(openingIndex<opening.length)setTimeout(showOpeningQuestion,450);else setTimeout(trickyQuiz,500)}
function trickyQuiz(){trickyIndex=0;showTricky()}
function showTricky(){let q=tricky[trickyIndex];render(7,`<div class="eyebrow">EVIDENCE 06.${trickyIndex+1} // TRICK QUESTIONS</div><h2>Read the question twice.</h2><p>${escapeHTML(q.q)}</p><div class="options">${q.a.map((a,i)=>`<button class="option" onclick="answerTricky(${i})"><span class="letter">${String.fromCharCode(65+i)}</span><span>${escapeHTML(a)}</span></button>`).join("")}</div><div id="trfb" class="feedback"></div><p class="small">The archive rewards attention, not speed.</p>`,8)}
function answerTricky(i){if(i!==tricky[trickyIndex].c){feedback("trfb","WRONG. Slow down, detective. Try again.");return}feedback("trfb","DETAIL VERIFIED.",true);trickyIndex++;if(trickyIndex<tricky.length)setTimeout(showTricky,450);else setTimeout(photoPuzzle,500)}
function photoPuzzle(){photoOrder=[0,1,2,3,4,5,6,7,8];do{photoOrder.sort(()=>Math.random()-.5)}while(photoOrder.every((v,i)=>v===i));selectedTile=null;render(8,`<div class="eyebrow">EVIDENCE 07 // DAMAGED IMAGE</div><h2>The memory is incomplete.</h2><p>The image has been divided into nine fragments. Reconstruct it to expose the final instruction.</p><div id="board" class="photo-board">${photoOrder.map((v,i)=>tile(v,i)).join("")}</div><p class="hint center">Tap one fragment, then another to swap them. Rebuild the photograph.</p><button class="primary" onclick="checkPhoto()">REASSEMBLE THE EVIDENCE</button><div id="phfb" class="feedback"></div><div class="rule"></div><p class="small">If the image does not appear, make sure assets/memory.jpg exists in your GitHub repository.</p>`,8)}
function tile(v,i){let r=Math.floor(v/3),c=v%3;return `<button class="tile${selectedTile===i?" selected":""}" aria-label="Photo fragment ${i+1}" style="background-image:url('${SETTINGS.photoPath}');background-position:${c*50}% ${r*50}%" onclick="selectTile(${i})"></button>`}
function selectTile(i){if(selectedTile===null){selectedTile=i;document.getElementById("board").innerHTML=photoOrder.map((v,k)=>tile(v,k)).join("");return}if(selectedTile===i){selectedTile=null}else{[photoOrder[selectedTile],photoOrder[i]]=[photoOrder[i],photoOrder[selectedTile]];selectedTile=null}document.getElementById("board").innerHTML=photoOrder.map((v,k)=>tile(v,k)).join("")}
function checkPhoto(){if(photoOrder.every((v,i)=>v===i)){feedback("phfb","IMAGE RESTORED. The final lock is yours to solve.",true);setTimeout(finalPuzzle,500)}else feedback("phfb","THE IMAGE IS STILL FRACTURED. Swap fragments until the photograph is whole.")}
function deriveCode(){// first-date day last digit=1; first-kiss day last digit=3; first-speaking month=2; official-relationship day last digit=7
return "1327"}
function finalPuzzle(){render(8,`<div class="eyebrow">ROOT FILE // FINAL CLEARANCE</div><div class="stamp">FINAL CLEARANCE REQUIRED</div><h2>The code was in the dates all along.</h2><p>You restored the timeline. Use four details to form the final access code.</p><div class="panel"><div class="panel-label">ROOT INSTRUCTION</div><p><strong>DIGIT 1</strong> — last digit of the day of our first date.</p><p><strong>DIGIT 2</strong> — last digit of the day of our first kiss.</p><p><strong>DIGIT 3</strong> — month we first started speaking.</p><p><strong>DIGIT 4</strong> — last digit of the day we officially became a couple.</p><p class="small">One digit per instruction. Enter them in the order shown.</p></div><label for="code">FOUR-DIGIT ACCESS CODE</label><input id="code" type="password" inputmode="numeric" maxlength="4" placeholder="••••"><button class="primary" onclick="checkCode()">REQUEST ROOT ACCESS</button><div id="cfb" class="feedback"></div>`)}
function checkCode(){let entered=document.getElementById("code").value.trim();if(entered===deriveCode()&&entered===SETTINGS.physicalLockCode){ending()}else if(entered===deriveCode()){feedback("cfb","DIGITAL CLUE SOLVED, BUT SETTINGS.physicalLockCode does not match. Check the configuration in script.js.")}else feedback("cfb","ACCESS DENIED. Revisit the four instructions. Each one extracts a single digit.")}
function ending(){document.getElementById("footerStatus").textContent="ROOT ACCESS GRANTED";document.getElementById("progressBar").style.width="100%";document.getElementById("progressText").textContent="ALL FILES RECOVERED";stageEl.innerHTML=`<div class="eyebrow" style="color:var(--green)">ROOT ACCESS GRANTED // CASE CLOSED</div><h1>Found you.</h1><p>The archive has released its final secret. The memories were never lost — only hidden in plain sight.</p><div class="panel"><div class="panel-label">FINAL INSTRUCTION</div><p style="margin:0">Use the code you just solved on the physical lockbox. Then look underneath the lid before removing anything inside.</p></div><div class="unlock">${deriveCode()}</div><p class="center small">THE BLACK ARCHIVE // FILE SEALED</p><div class="rule"></div><p class="quote center">Some memories don't need to be recovered.<br>They just need to be remembered.</p>`}
openingScreen();